
development:
  adapter: mysql2
  encoding: utf8
  database: moments_developement
  host: localhost
  username: root
  password: root

test: 
  adapter: mysql2
  encoding: utf8
  database: moments_development
  host: localhost
  username: root
  password: root
